name: video-search
channels:
  - conda-forge
dependencies:
  - python=3.6
  - numpy=1.15
  - pandas=0.24
  - matplotlib=3.0
  - seaborn=0.9
  - jupyterlab=1.1
  - scikit-learn=0.21
  - pillow=7.0.0
  - ipywidgets
  - requests
  - nodejs
  - dlib
  - tqdm
  - pip
  - pip:
    - opencv-python
